### ISSUE TITLE
Update to NestJS 8.0 / Errors

### ISSUE THREAD

**Issue by woltob** [mikro-orm/nestjs-example-app#14] opened 2021-08-11 15:47 UTC
Hi,

I quickly tried upgrading my NestJS packages to v8 (coming from v7) and was finding an error that said 

`EntityManager`  was not imported / is not available in the  UserModule (showing the Service that uses the em below).

There is likely something wrong with importing the EntityManager and injecting it.

Could you bump this project up to use the newest versions of NestJS and resolve any issues that might appear?

Thanks!

```
@Injectable()
export class UserService {
  constructor(
    @Inject(forwardRef(() => UserService))
    private readonly userService: UserService,
    private em: EntityManager<PostgreSqlDriver>,
  ) {}
}
```

**Comment by B4nan** [comment] 2021-08-11 16:31
Duplicate of https://github.com/mikro-orm/nestjs/issues/27, the repository will be updated once nest 8 is officially supported, you can subcribe there.

**Closed as completed by B4nan** 2021-08-11 16:31 UTC
